version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: stop.sh
  BeforeInstall:
    - location: pull.sh
  Install:
    - location: start.sh
  AfterInstall:
    - location: clean.sh
