version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: stop.sh
  
  Install:
    - location: pull.sh
  
  ApplicationStart:
    - location: start.sh
  
  
